---
title: "Final" 
author: "Yuechen Liu, Mufeng Xu, Yanhao Li"
output:
  pdf_document:
    toc: yes
    toc_depth: 2
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '2'
header-includes:
- \usepackage{fancyhdr}
- \usepackage{lipsum}
- \pagestyle{fancy}
- \fancyhead[R]{\thepage}
- \fancypagestyle{plain}{\pagestyle{fancy}}
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```


\newpage

```{r}
library(tidyverse)
library(caret)
library(glmnet)
library(ISLR)
library(pls)
library(AppliedPredictiveModeling)
library(MASS)
library(e1071)
library(mlbench)
library(pROC)
```

Load, clean, and tidy data

```{r}
stroke = read_csv("./healthcare-dataset-stroke-data.csv") %>% 
  janitor::clean_names() %>% 
  filter(
    bmi != "N/A"
  ) %>% 
  mutate(
    gender = recode(
      gender,
      "Male" = 0,
      "Female" = 1,
      "Other" = 2
    ),
    ever_married = recode(
      ever_married,
      "No" = 0,
      "Yes" = 1
    ),
    work_type = recode(
      work_type,
      "children" = 0,
      "Govt_job" = 1,
      "Never_worked" = 2,
      "Private" = 3,
      "Self-employed" = 4
    ),
    residence_type = recode(
      residence_type,
      "Rural" = 0,
      "Urban" = 1
    ),
    smoking_status = recode(
      smoking_status,
      "formerly smoked" = 0,
      "never smoked" = 1,
      "smokes" = 2,
      "Unknown" = 3
    ),
    bmi = as.numeric(bmi),
    stroke = as.factor(stroke)
  )

stroke2 = stroke %>% 
  mutate(
    gender = as.factor(gender),
    hypertension = as.factor(hypertension),
    heart_disease = as.factor(heart_disease),
    ever_married = as.factor(ever_married),
    work_type = as.factor(work_type),
    residence_type = as.factor(residence_type),
    smoking_status = as.factor(smoking_status)
  )
```

# Visualization

```{r}
transparentTheme(trans = .4)

featurePlot(x = stroke[, 2:11], 
            y = stroke$stroke,
            scales = list(x = list(relation = "free"), 
                        y = list(relation = "free")),
            plot = "density", pch = "|", 
            auto.key = list(columns = 2))
```

# Perform logistic regression with "stroke" as the response and all other variables except "id" as predictors

```{r}
set.seed(1)

indextrain <- createDataPartition(y = stroke2$id,
                               p = 0.9,
                               list = FALSE)

train <- stroke2[indextrain, ]

test <- stroke2[-indextrain, ]
  
glm.fit <- glm(stroke ~ gender + age + hypertension + heart_disease + ever_married + work_type + residence_type + avg_glucose_level + bmi +smoking_status, 
               data = train, 
               family = binomial)

summary(glm.fit)
```

# Compute confusion matrix 

```{r}
prob = predict(glm.fit,
               newdata = test,
               type = "response")

pred = rep("0", length(prob))

pred[prob > 0.5] = "1"

confusionMatrix(data = as.factor(pred),
                reference = test$stroke,
                positive = "1")
```

# Fit logistic regression model using the training data with age, hypertension, and average glucose level as predictors

```{r, fig.height=20, fig.width=20}
glm.fit2 <- glm(stroke ~ age + hypertension + avg_glucose_level, 
               data = train, 
               family = binomial)

summary(glm.fit2)

prob2 = predict(glm.fit2,
                newdata = test,
                type = "response")

roc.glm2 <- roc(test$stroke, prob2)

plot(roc.glm2, legacy.axes = TRUE, print.auc = TRUE)

plot(smooth(roc.glm2), col = 4, add = TRUE)
```

# Repeat using LDA and QDA

```{r, fig.height=20, fig.width=20}
lda.fit <- lda(stroke ~ age + hypertension + avg_glucose_level, 
               data = train)

prob3 = predict(lda.fit,
                newdata = test)

roc.lda <- roc(test$stroke, prob3$posterior[,2])

plot(roc.lda, legacy.axes = TRUE, print.auc = TRUE)

plot(smooth(roc.lda), col = 4, add = TRUE)

qda.fit <- qda(stroke ~ age + hypertension + avg_glucose_level, 
               data = train)

prob4 = predict(qda.fit,
                newdata = test)

roc.qda <- roc(test$stroke, prob4$posterior[,2])

plot(roc.qda, legacy.axes = TRUE, print.auc = TRUE)

plot(smooth(roc.qda), col = 4, add = TRUE)
```

# Repeat using KNN

```{r, fig.height=20, fig.width=20}
set.seed(1)

train_cl = train %>%
  dplyr::select(age, hypertension, avg_glucose_level, stroke) %>% 
  mutate(
    stroke = recode(
      stroke,
      "0" = "No",
      "1" = "Yes"
    )
  )

test_cl = test %>%
  dplyr::select(age, hypertension, avg_glucose_level, stroke) %>% 
  mutate(
    stroke = recode(
      stroke,
      "0" = "No",
      "1" = "Yes"
    )
  )

ctrl <- trainControl(method = "repeatedcv",
                     repeats = 5,
                     summaryFunction = twoClassSummary,
                     classProbs = TRUE)

knn.fit <- train(x = train_cl[1:3],
                   y = train_cl$stroke,
                   method = "knn",
                   metric = "ROC",
                   preProcess = c("center", "scale"),
                   tuneGrid = data.frame(k = seq(1, 200, by = 5)),
                   trControl = ctrl)

ggplot(knn.fit)

prob5 = predict(knn.fit,
                newdata = test_cl,
                type = "prob")

roc.knn <- roc(test_cl$stroke, prob5$Yes, levels = c("No", "Yes"))

plot(roc.knn, legacy.axes = TRUE, print.auc = TRUE)

plot(smooth(roc.knn), col = 4, add = TRUE)
```

